### ISSUE TITLE
too many file descriptors in select()

### ISSUE THREAD

**Issue by CL545740896** [authorizon/fastapi_websocket_pubsub#12]
ValueError: too many file descriptors in select()
windows10  
python3.7
when clients connect  more than 500 , server will have shutdown 
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

**Comment by orweis** [comment]
Hey Eric, :) 

Your issue seems related to this https://stackoverflow.com/questions/47675410/python-asyncio-aiohttp-valueerror-too-many-file-descriptors-in-select-on-win - and asyncio implementation on windows. 

Can you please share the full stack trace / exception? So we can see where you got the error from.
Also please include s sample of your code using the package.

**Comment by orweis** [comment]
Hi @CL545740896 I dove deeper into the subject - seems that switching your server to work with [asyncio.ProactorEventLoop](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.ProactorEventLoop) should resolve your issue.

 There are two easy changes you can apply to achieve this:
 1. Upgrading to Python 3.8 or newer (where ProactorEventLoop is the default for Windows)
 2. Setting the [policy](https://docs.python.org/3/library/asyncio-policy.html#policy-objects) to use it by calling set policy (before sever start), like this:
 ```python
 asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
 ```
 
I'm closing the issue; feel free to reopen it, if the problem persists.
